name: Terraform CI/CD with Lambda Packaging

on:
  push:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Setup Python for packaging
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install Pillow dependency for Linux Lambda
      run: |
        mkdir lambda_package
        pip install --platform manylinux2014_x86_64 --target lambda_package --implementation cp --python-version 3.9 --only-binary=:all: Pillow

    - name: Copy Lambda function code
      run: |
        cp main.py lambda_package/

    - name: Zip lambda deployment package
      run: |
        cd lambda_package
        zip -r ../image_processor.zip .

  - name: Move packaged lambda zip to terraform directory
    run: |
      mv image_processor.zip terraform/
        
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.4.0

    - name: Terraform Init
      working-directory: terraform
      run: terraform init

    - name: Terraform Validate
      working-directory: terraform
      run: terraform validate

    - name: Terraform Plan
      working-directory: terraform
      run: terraform plan

    - name: Terraform Apply
      working-directory: terraform
      if: github.ref == 'refs/heads/main'
      run: terraform apply -auto-approve
